### PR TITLE
Adding two methods get and Count

### PR DESCRIPTION
**Pull request by JulianMendezw**
Update DBStorage and FileStorage, adding two new methods. All changes should be done in the branch storage_get_count:

A method to retrieve one object:

Prototype: def get(self, cls, id):
cls: class
id: string representing the object ID
Returns the object based on the class and its ID, or None if not found
A method to count the number of objects in storage:

Prototype: def count(self, cls=None):
cls: class (optional)
Returns the number of objects in storage matching the given class. If no class is passed, returns the count of all objects in storage.

check it out!

### CODE REVIEW

**Comment by Giraluna1** [comment]
how are you passing the parameters in the count method?

**Comment by JulianMendezw** [comment]
We are using a file call test_get_count.py to know if the method works **#SOSColombia** @🟨🟦🟥

**Comment by Giraluna1** [comment]
Cool. Your methods work great!

**Comment by Giraluna1** [comment]
Only Run

**Comment by JulianMendezw** [comment]
Thanks but not thanks💔

**Pull request merged**
